<?php

define("commonfare_pages", [
  "about" => 24,
  "get_informed" => 25,
  "participate" => 26,
]);

function render_page($nid) {
  $entity_type = 'node';
  $view_mode = 'full';
  $node = \Drupal::entityTypeManager()->getStorage($entity_type)->load($nid);
  $view_builder = \Drupal::entityTypeManager()->getViewBuilder($entity_type)->view($node, $view_mode);
  $output = render($view_builder);
  return $output;
}

function commonfare_ui_preprocess_page__front(array &$variables)
{

  $variables['page']['learn_how'] = t("Learn How");

  $pages = \Drupal::config('commonfare_ui.settings')->get('pages');
  if (!$pages) {
    $config = \Drupal::service('config.factory')->getEditable('commonfare_ui.settings');
    $config->set('pages', commonfare_pages);
    $pages = commonfare_pages;
  }

  foreach ($pages as $label => $nid) {
    $variables['page'][$label] = render_page($nid);
  }

}
