<?php

define("commonfare_pages", [
  "about" => 24,
  "get_informed" => 25,
  "participate" => 26,
]);


function commonfare_ui_render_page($nid) {
  $entity_type = 'node';
  $view_mode = 'full';
  $node = \Drupal::entityTypeManager()->getStorage($entity_type)->load($nid);
  $view_builder = \Drupal::entityTypeManager()->getViewBuilder($entity_type)->view($node, $view_mode);
  $output = render($view_builder);
  return $output;
}

function commonfare_ui_get_pages() {
  $pages = \Drupal::config('commonfare_ui.settings')->get('pages');
  if (!$pages) {
    $config = \Drupal::service('config.factory')->getEditable('commonfare_ui.settings');
    $config->set('pages', commonfare_pages);
    $pages = commonfare_pages;
  }
  return $pages;
}

function commonfare_ui_preprocess_page__front(array &$variables)
{

  $variables['page']['txts'] = [
    'next' => t("Next"),
    'prev' => t("Previous"),
    'summary' => t("Summary"),
    "learn_how" => t("Discover"),
    "cat" => t("Categories"),
    "lang" => t("Language"),
    "please_select" => t("Please select the country of your interest"),
    "sorry_no_lang" => t("Sorry, this content is not available in your language"),
    "i_am_in" => t("I am in"),
    "subscribe" => t("Keep me updated"),
    "copyright" => t("Commonfare.net is a PIE News Project"),
    "email" => t("name@domain.com"),
  ];

  $variables['page']['learn_how'] = $variables['page']['txts']['learn_how'];
  $variables['page']['subscribe'] = $variables['page']['txts']['subscribe'];
  $variables['page']['email'] = $variables['page']['txts']['email'];
  $variables['page']['copyright'] = $variables['page']['txts']['copyright'];


  $pages = commonfare_ui_get_pages();
  foreach ($pages as $label => $nid) {
    $variables['page'][$label] = commonfare_ui_render_page($nid);
  }

}

// function commonfare_ui_system_breadcrumb_alter(\Drupal\Core\Breadcrumb\Breadcrumb &$breadcrumb, \Drupal\Core\Routing\RouteMatchInterface $route_match, array $context) {
//   // Add an item to the end of the breadcrumb.
//   $breadcrumb = new \Drupal\Core\Breadcrumb\Breadcrumb();
//   // $breadcrumb->addLink(\Drupal\Core\Link::fromTextAndUrl(t('Text'), new \Drupal\Core\Url('<none>')));
//
//   $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
//
//   $pages = commonfare_ui_get_pages();
//   $node = \Drupal::entityTypeManager()->getStorage('node')->load($pages['get_informed']);
//
//   $node = $node->getTranslation($language);
//
//   // $url_object = Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => $node->id]);
//   // $breadcrumb->addLink(\Drupal\Core\Link::fromTextAndUrl($node->getTitle(), $url_object));
//
//   //   kint($context, $node->id);
// }
